### ISSUE TITLE
Help with Ramp target?

### ISSUE THREAD

**Issue by steampunk15** [siteswapjuggler/RAMP#13]

**Comment by siteswapjuggler** [comment]
Did you find a solution ? I've been off the web for the past few day and didn't saw you original post in the first place.

**Comment by steampunk15** [comment]
Many thanks for your reply.
I've sort of got it working but would appreciate if you could tell me if
it's possible to reset the Ramp to 0 easily ?
I want to use it repeatedly in a "loop" with different target values to
ramp to, some positive values, and some negative?
Kind regards,
Neil

**Comment by siteswapjuggler** [comment]
Yes sure if you call myRamp.go(value) it goes directly to this value. 
You could also work with continuous ramp this way myRamp.go(target,duration,LINEAR,LOOPFORWARD) or play with the isFinished() method.

Can you be more specific about the animation you want to achieve ?

**Comment by steampunk15** [comment]
Thanks so much for your help, I'm out at the moment, I will send you a more
detailed plan of what I trying to do achieve  later today.
Kind regards.
Neil

**Comment by steampunk15** [comment]
Hi Sylvain,

My plan is to use the ‘Ramp’ function to assist with the position  2 servos.

The ’Target’ values for the ramp may vary from +150 to -150, and will be added to a value derived from an array.
These will then be used to deliver the required position of the servo over the duration of the Ramp.

The ’Target’ and ’Servo_Value’ will be from an ‘array [60]’

A friend has helped with the code shown below which sort of works, but I wondered if there is a better way to get the Ramp reset to 0 

NB this is obviously a very basic outline of what I’m trying to do. My knowledge of C++ is very limited, but I could see that your ‘Ramp’ function is going to be ideal for positioning servos over a timed duration.

Given that I’m using 2 servos (possibly more at a later date), everything below will be x2; ie 

myRamp1.go(Target1, Ramp_Duration);
myRamp2.go(Target2, Ramp_Duration);
etc.

I hope this makes some sort of sense?

Kind regards,
Neil



void loop() {

    
  if (myRamp.isRunning() == false){  
    
    myRamp.go(Target, Ramp_Duration);
  }

  if (myRamp.isRunning() == true){  

    Ramp_Value = myRamp.update();
       
   
     pwm.setPWM(SV1, 0, (Ramp_Value + array[count] ));  }

  if(Ramp_Value == Target){
   
    if(Target >20 || Target<20){  //Make sure we don't reset the target to 0+1 when resetting back to 0.
     Target = Target - 1   
	count = count + 1;
    	count = count + 1;
     if (count == 60){
      count = 0;
     }
     
    }
    myRamp.go(0,20); // reset to 0 very quickly
  }
}

**Comment by siteswapjuggler** [comment]
Hmmm still confused with your code, especially the adjustment of target compare to the values in your array.

Also if you want values from -150 to 150 you should use rampInt type instead of ramp (which is a Byte)

**Comment by steampunk15** [comment]
Morning Sylvain,

I apologies for my very poorly written code, I have included what I have in full below.

The first code actually works!!!!, but I know it's very messy and could be vastly improved.

The purpose of the finished code is to position 4 servos (via a PCA9685) that will operate some animatronic eyes, these fit inside a ’Steampunk’ camera.
The finished camera will actually take photographs, plus play sound effects from the horn mounted on the top, (which will also emit smoke)!!!
The flashgun on the side also opens/closes via another servo and fires the flash.


I have a single servo working (see 1st code below), I need to modify the code to operate 2 ramps simultaneously, this where Im having some problems.
The 2 ramps will take ’Target’ values from arr[count] [0], and from arr[count] [1]. These values are for either ‘Eye’ or Eyelid’ movements

I can  decide if the servo movement required if for the ‘Eyes’ or ‘Eyelids’ based on if (( arr [count] [0]) == RO || (arr [count] [0]) == RC == true){

This is because the ‘Eyelids’ have some movement values unique only to  them, 

My logic is:

Read the array value from arr[count] [0]
Determine if movement is for ‘Eyes’ or Eyelids’

If ‘Eye’ movement, then:

pwm.setPWM(SV1, 0, (Ramp_Value + arr[count] [0])); // Eye vertical movement
pwm.setPWM(SV2, 0, (Ramp_Value + arr[count] [1])); // Eye horizontal movement


If ‘Eyelid’ movement, then:

pwm.setPWM(SV3, 0, (Ramp_Value + arr[count] [0])); // Right Eyelid movement
pwm.setPWM(SV4, 0, (Ramp_Value + arr[count] [1])); // Left Eyelid movement

The code in BLUE obviously will not work, it's just to show my ‘logic’ (I know this would never work as written)!!!!!

Kind regards,
Neil


#include <Ramp.h>

#include <Adafruit_PWMServoDriver.h>
#define SERVOMIN  125 // this is the 'minimum' pulse length count (out of 4096)
#define SERVOMAX  575 // this is the 'maximum' pulse length count (out of 4096)
Adafruit_PWMServoDriver pwm = Adafruit_PWMServoDriver();

//SDA=purle pin4



rampInt myRamp1;
rampInt myRamp2;

int Ramp_Value1;
int Ramp_Duration1;
int Target1;

int S1 = 20; // Ramp_Duration  (speed of servo movement)
int S2 = 1000;
int S3 = 2000;
int S4 = 3000;

int D0 = 150; //  Delay to next servo movement
int D1 = 1000;
int D2 = 2000;
int D3 = 3000;
int D4 = 4000;
int D5 = 5000;
int D6 = 500;

int C = 390; // Centre // eye servo positions
int U = 340; // Loop up // eye servo positions
int D = 440; // Look down // eye servo positions
int L = 340; // Look left // eye servo positions
int R = 440; // Look right // eye servo positions

int RO = 400; // Right eyelid open (lower No. = more open)
int LO = 380; // Reft eyelid open (higher No. = more open)
int RC = 485; // Right eyelid closed (higher No. = more closed)
int LC = 315; // Reft eyelid closed (lower No.= more closed)

int count = 0;
int lastpos1 = 390; // The value must = "C" in "void Setup" (pwm.setPWM(SV4, 0, C )
int SV4 = 4; 

int arr [60][4] =   { // count is from 0 to 59
  {C,L,S1,D1}, // count 0 = 1st row
  {C,R,S1,D2}, 
  {C,C,S2,D2},
  {RC,LC,S1,D0},
  {RO,LO,S1,D3},
  {U,C,S2,D2},
  {D,C,S3,D3},
  {C,C,S3,D3},
  {D,R,S1,D2},
  {U,R,S3,D3},
  {C,R,S3,D2},
  {C,C,S1,D1},
  {RC,LC,S1,D1},
  {RO,LO,S1,D0},
  {RO,LO,S1,D5},
  {U,L,S2,D2},
  {D,L,S3,D2},
  {D,R,S3,D2},
  {U,R,S3,D2},
  {U,L,S3,D2},
  {C,L,S3,D2},
  {C,C,S1,D3},
  {C,C,S1,D3},
  {RC,LC,S1,D0},
  {RO,LO,S1,D3},
  {RC,LC,S1,D0},
  {RO,LO,S1,D3},
  {RC,LC,S4,D3},
  {RO,LO,S1,D0},
  {C,R,S1,D6},
  {C,L,S1,D6},
  {C,R,S1,D6},
  {C,C,S1,D1},
  {RC,LC,S1,D0},
  {RO,LO,S1,D3},
  {D,R,S2,D1},
  {D,L,S3,D1},
  {C,C,S1,D3},
  {RC,LC,S4,D3},
  {RC,LO,S3,D1},
  {RC,LC,S4,D2},
  {RO,LO,S1,D1},
  {C,R,S1,D6},
  {C,L,S1,D6},
  {C,C,S1,D1},
  {RC,LC,S1,D0},
  {RO,LC,S1,D0},
  {RC,LC,S1,D0},
  {RO,LO,S1,D1},
  {RO,LO,S1,D1},
  {U,C,S2,D2},
  {U,L,S1,D1},
  {U,R,S1,D1},
  {C,C,S1,D3},
  {RC,LC,S1,D0},
  {RO,LC,S1,D3},
  {RC,LO,S1,D1},
  {RO,LC,S1,D1},
  {RC,LO,S1,D1},
  {RO,LO,S1,D1}, 
};

void setup() {
  Serial.begin(9600);
  
  pwm.begin();
  pwm.setPWMFreq(60);  // Analog servos run at ~60 Hz updates
  
  pwm.setPWM(SV4, 0, C ); 
  delay(1000);

}

void loop() {
  
  if (myRamp1.isRunning() == false){  
    Serial.println("Start");
    Target1 = (arr[count] [0] - lastpos1);
    lastpos1 = arr[count] [0];
    Ramp_Duration1 = arr[count] [2];
 
    Serial.print("Target1 = ");
    Serial.println(Target1);
    myRamp1.go(Target1, Ramp_Duration1);
  }

  if (myRamp1.isRunning() == true){  //test to see if ramp is running
    Ramp_Value1 = myRamp1.update();
    
    Serial.print("Ramp Vaule = ");
    Serial.println (Ramp_Value1 + arr[count] [0]); 
    
    pwm.setPWM(SV4, 0, (Ramp_Value1 + arr[count] [0])); // Moves servo to position over prescribed time.
   
  }

  if(Ramp_Value1 == Target1){
    Serial.print("Target1 reached");
    Serial.print("    COUNT = ");
    Serial.println(count);
    if(Target1 >20 || Target1<20){  //Make sure we don't reset the target to 0+1 when resetting back to 0.
     Target1 = Target1 - 1;
     
     count = count + 1;
     if (count == 60){
      count = 0;
     }
     
    }
    myRamp1.go(0,20);
  }
}


*************************************************************************
void setup() {
  Serial.begin(9600);
  pwm.begin();
  pwm.setPWMFreq(60);  // Analog servos run at ~60 Hz updates

  pwm.setPWM(SV1, 0, C ); // position eye vertical center ***lastpos1
  pwm.setPWM(SV2, 0, C ); // position eye horizontal center ***lastpos2
  pwm.setPWM(SV3, 0, LO ); // position left eyelid open ***lastpos3
  pwm.setPWM(SV4, 0, RO ); // position right eyelid open ***lastpos4
   
  delay(2000);
  
      
}
   
void loop() {
  
  
   
  if (( arr [count] [0]) == RO || (arr [count] [0]) == RC == false){ // determines that Eye servos are used
    if (myRamp1.isRunning() && myRamp2.isRunning()== false){
      
      Target1 = (arr[count] [0]) - (lastpos1); // last position of left eye
      Target2 = (arr[count] [1]) - (lastpos2); // last position of right eye
      
      lastpos1 = arr[count] [0]; // sets last position for next time round loop
      lastpos2 = arr[count] [1]; // sets last position for next time round loop    
      
      myRamp1.go (Target1, arr[count] [2]); // pos1 = ramp target,  & arr[count] [2] is ramp speed/duration
      myRamp2.go (Target2, arr[count] [2]); // pos2 = ramp target,  & arr[count] [2] is ramp speed/duration
    }
    
    if (myRamp1.isRunning() && myRamp1.isRunning() == true){  //test to see if ramp is running
           
      Ramp_Value1 = myRamp1.update();
      Ramp_Value2 = myRamp2.update();      

      pwm.setPWM(SV1, 0, (Ramp_Value1 + arr[count] [0])); // set eye vertical servo to new position via ramp
      pwm.setPWM(SV2, 0, (Ramp_Value2 + arr[count] [1])); // set eye horizontal servo to new position via ramp
      
      if (myRamp1.isFinished() && myRamp2.isFinishe){ 
        Serial.println ("Eyelid move Finished");  
      }

       if (( arr [count] [0]) == RO || (arr [count] [0]) == RC == true){  // determines that Eyelid servos are used
        Target1 = (arr[count] [0]) - (lastpos3); // last position of left eyelid
        Target2 = (arr[count] [1]) - (lastpos4); // last position of right eyelid
      
        lastpos3 = arr[count] [0]; // sets last position for next time round loop
        lastpos4 = arr[count] [1]; // sets last position for next time round loop
      
        myRamp1.go (Target1, Ramp_Duration1); // pos1 = ramp target,  & arr[count] [2] is ramp speed/duration
        myRamp2.go (Target2, Ramp_Duration2); // pos2 = ramp target,  & arr[count] [2] is ramp speed/duration
    
    }
    if (myRamp1.isRunning() && myRamp1.isRunning() == true){  //test to see if ramp is running
           
      Ramp_Value1 = myRamp1.update();
      Ramp_Value2 = myRamp2.update();      

      pwm.setPWM(SV3, 0, (Ramp_Value1 + arr[count] [0]));
      pwm.setPWM(SV4, 0, (Ramp_Value2 + arr[count] [1]));
    }
       
     
    if (myRamp1.isFinished() && myRamp2.isFinished()){      
        Serial.println ("Eyelid move Finished");     
         if(Target1 >20 || Target1<20){  //Make sure we don't reset the target to 0+1 when resetting back to 0.
          Target1 = Target1 - 1;
          count = count + 1;
            if (count == 60){
            count = 0;
            }
            myRamp1.go(0,20); 
            myRamp2.go(0,20);
         }

**Comment by steampunk15** [comment]
Hi Sylvain,
Hope you are well and have not got the dreaded virus!
Did you get my last email and did it make any sense at all?
Many thanks,
Neil

**Comment by siteswapjuggler** [comment]
If I understand well you array stores 60 of those information : 
motor1_pos, motor2_pos, duration_to_go_to_those_position, pause_before_next_move

And you want your program to scroll in loop over those 60 positions :
gotopos1, wait1, gotopos2, wait2 etc...

Do I understand correctly ?

**Comment by steampunk15** [comment]
Yes, two servos, two ramps running at the same time.
Neil

**Comment by siteswapjuggler** [comment]
This should do the trick for one servo and should give you the appropriate structure to add the second one : https://pastebin.com/r8PGgZxy

**Comment by steampunk15** [comment]
Thank you, I will try it later when I finish work
Kind regards,
Neil

**Comment by steampunk15** [comment]
Excellent, it worked fine.
Thank you very much for your help, I've learnt a lot.
Kind  regards.
Neil

**Comment by steampunk15** [comment]
Hi  Sylvain,
I hope you are well?

Thanks to you help I managed to animate the ‘eyes’ and ‘eyelids’ exactly as I had hoped.
Although the code works fine, I’m sure it could improved!

I would be very grateful for your assistance again in applying your ramp function.

I require a dedicated sequence to initiate following a ‘button press’.
Within this sequence there are a number of servo animations that I would like to apply the ramp function too, regrettably I have not been able to get it to work?

I have included a very simple version of the type of structure within the ‘button press’. This only shows a single servo animation, however, when complete it will animate 5 different servos through a number of sequential animations. The sequence of animations will also include a number of actions, ie LED’s, MP3 tracks, smoke generation , etc.

One this sequence has completed, it will revert back to the ‘loop’ animation following a reset. Hopefully this makes some sense.

I have included the working animation and also the basic ‘structure’ of the button press.

Kind regards,
Neil.  

(UK, England).

**Comment by siteswapjuggler** [comment]
Sorry I've been away from Github for a while. Did you manage to get your project working or do you still need help ?

Sylvain

**Comment by steampunk15** [comment]
Thank you for getting back to me, yes its working fine. Thank you again for your help.
Kind regards,
Neil

**Comment by steampunk15** [comment]
Hi Sylvain,

I hope you are well?


The animations work fine, the only current problem I have is with the delay between the animations.
As you will see, the basic first program you helped me with now has 4 servos instead of one.

The current delay works perfectly  (line 416), however, I would like to replace it with a  ’non blocking’ millis delay? 

I tried placing the mills delay as shown, this does not work correctly though. There is only a delay, if the delay time is > the ramp time, the delay is then only the difference between the two.

If the ramp time is 1 second, and the delay is 2 seconds, the actual delay is only 1 second.

Its obviously my placement of the millis delay?

Any help would be very appreciated.

Kind regards,

Neil

**Comment by siteswapjuggler** [comment]
Hi Neil,

did you make it work ? I do not see the newest program you talk about can you paste it to https://pastebin.com/ so I can have a proper look on it ?

++
Sylvain

**Comment by steampunk15** [comment]
Hi Sylvain,
Regrettably I have not managed to fix the delay problem.

I would like to replace line 458 (delay(animation[index][5]);) with a non-blocking delay

Steampunk Camera -  <https://pastebin.com/WjLY7dwk>Pastebin.com <http://pastebin.com/>

Kind regards,
Neil

**Comment by siteswapjuggler** [comment]
There is a way to do it by adding ramp to the same number... Per example starting at 0, go at 100 in 1000 ms, then go at 100 in 500 ms when the first ramp is finished (this second ramp will not affect the value and will act like a non blocking delay).

The other way to do it is via state diagram, with a variable that store the "state" of your animation (waiting, ongoing) when all the ramp are finished the state become "waiting" and you store the actual millis in a long variable. Then you test for millis to be >= to the value stored + your delay and if true you can trigger your new ramp and have the state "ongoing"

Sates are a way to execute code depending on the actual state of your programm.

Does that help ?

**Comment by steampunk15** [comment]
Hi Sylvain,
Many thanks for your reply, unfortunately my knowledge of C++ is very limited and I’m not sure I understand correctly, would it be possible to send example please.
Thank you,
Neil

**Comment by siteswapjuggler** [comment]
Per example in your animation array you can add intermediate value to create false "delay". 

Per example line 159 :
{CENTER,CENTER,         RIGHT_CLOSED,LEFT_CLOSED,   SPEED_70,DELAY_100},

You can add : 
{CENTER,CENTER,         RIGHT_CLOSED,LEFT_CLOSED,   SPEED_70,DELAY_1000},

Doing so your code will take this next step as the next animation but since all the value are the same it will not animate any value but just wait for the delay to finish before the method isFinished() would be true again

**Comment by steampunk15** [comment]
Hi Sylvain, Sorry I still can’t see how this will work?

Currently the delay is applied by:     delay(animation[index][5]

If I were to add additional lines:
Per example line 159 :
{CENTER,CENTER, RIGHT_CLOSED,LEFT_CLOSED, SPEED_70,DELAY_100},

You can add :
{CENTER,CENTER, RIGHT_CLOSED,LEFT_CLOSED, SPEED_70,DELAY_1000},

Surely all I will do is add more blocking delays?

Thanks,
Nei

**Comment by siteswapjuggler** [comment]
Sorry I didn't read your code completely so let's say 

{CENTER,CENTER, RIGHT_CLOSED,LEFT_CLOSED, SPEED_70},
{CENTER,CENTER, RIGHT_CLOSED,LEFT_CLOSED, DELAY_1000},

In this way you don't need to use delay(animation[index][5]) the delay will just be a ramp to itself within the expected delay duration.

**Comment by steampunk15** [comment]
I can see how that will work, but that will mean that I will have to add 130 lines to the index, is that correct?
Thanks,
Neil

**Comment by siteswapjuggler** [comment]
Yes it will do something like that, it's just a quick hack considering your actual knowledge in cpp. But if you have enough memory in your controller it'll do the trick.

**Comment by steampunk15** [comment]
Thank you for your help.
Kind regards,
Neil.
