### ISSUE TITLE
Is the ramp target can only be an unsigned char? 

### ISSUE THREAD

**Issue by Peter-haotian-cui** [siteswapjuggler/RAMP#14]
I found that go function target value is unsigned char. The range is only 0~255, that is not enough for my application. Is that possible to expand the target value range?
![image](https://user-images.githubusercontent.com/38802432/77226271-06c2c580-6bb2-11ea-93d5-e4d12eca34d6.png)

**Comment by Peter-haotian-cui** [comment]
I just figure it out.
![image](https://user-images.githubusercontent.com/38802432/77226377-da5b7900-6bb2-11ea-8e93-668475cd6055.png)

**Comment by siteswapjuggler** [comment]
Good job, still have to do more exemple at one point :)
