### ISSUE TITLE
setAutomation: what's it for?

### ISSUE THREAD

**Issue by nburge** [siteswapjuggler/RAMP#15]
Hello. Just getting started with the ramp library. I'm curious about the setAutomation method. Could you please explain what it's for and how to use it? Ideally I'd like to be able to trigger a ramp using a button switch or some other "cue" and have the ramp run to it's conclusion even when the switch is released. Is this possible?

**Comment by siteswapjuggler** [comment]
setAutomation is true by default it activate an internal millis count which update the ramp value at the desired grain (by default every 10ms).

Setting it to false allow you to manage this grain/update manually in your code. It's usefull to save ressources when you have many ramp in the same code.

**Comment by nburge** [comment]
Thanks, that is what I'm looking to achieve. A way of running several ramps simultaneously, each being triggered to run from a midi device with note on/note off.

**Comment by siteswapjuggler** [comment]
The point you should take care of is that when autmation is of the duration become an abstract value. Let's say your ramp is done in 1000 units and your gain is set to 10 each update will progress by 10 within this 1000 units. So after let's say 3 update your progression in the ramp will be 30/1000.

**Comment by nburge** [comment]
THANKS getting the hang of it now. Great tool.
