### ISSUE TITLE
duration = 0 don't go to target value

### ISSUE THREAD

**Issue by patricecolet** [siteswapjuggler/RAMP#16]
Hello Sylvain! I'd like to use ramp for the enveloppe generator of my analog synth controlled with arduino.
 This library is neat but in some cases I expect myRamp(255,0) to go directly to the target value 255, but this doesn't work. So I have to apply the lowest duration value with myRamp(255,1).
Unfortunately this is not a good thing because it can add 1ms latency in the audio process.

**Comment by patricecolet** [comment]
I've found in the source code how to do without duration with myRamp(myValue) and no duration.

**Comment by siteswapjuggler** [comment]
Hello Patrice,

I updated the library so that ramp(val,0) will have the same result as ramp(val). Thanks a lot for your report.

Sylvain
