### ISSUE TITLE
Operation question please

### ISSUE THREAD

**Issue by PlanetariumWSD** [siteswapjuggler/RAMP#17]
Hello and thank you for creating this library!
We’d like to use RAMP in a light fading project and I have noticed unexpected behavior but it might be normal and I am not understanding RAMP’s intent.
**Goal:**
“Fade up”- Produce linear values from 0 to 10000 over 5 seconds.
“Fade down” - linear values from 10000 down to 100 over 5 seconds.

**Code and results:**
Using your basic included example:
UnInt16Bit ramp.go( val, dur, rampmode, loopmode);
ramp.go(10000, 5000ms, 1 [linear], 0 [onceForward] )
Results? a beautiful, smooth fade up to step 10,000! Perfect!
Next..
ramp.go(100, 5000ms, 1 [linear], 0 [onceForward] )  
Results? Values climb UP to 65536 then roll over to 0 and climb up and stop at step 100.

**I also tried..**
ramp.go(10000, 5000ms, 1 [linear], 0 [onceForward] )
Results? a smooth fade up to step 10,000!
Next...
  ramp.go(100, 5000ms, 1 [linear], **_**3 [onceBackwards]**_** )    
Results? a sudden pop to ~65536 and a slow fade down to 100.

Can RAMP interpolate between 2 non max values both up or down (without rolling over) and if so, could you provide a few example lines you would use to achieve this or any other guidance. It would be greatly appreciated.
Thank you!
-Chris

**Comment by siteswapjuggler** [comment]
Hello Chris,

thanks for your report. It's actually a bug with unsigned type. I just made a correction. The push is on it's way.

Sincerely
Sylvain

**Comment by PlanetariumWSD** [comment]
Oh WOW Sylvain! This is amazing! 
Thanks for your attention and work. I will engage your new version to the project ASAP and update this thread with results. 
:-)

**Comment by PlanetariumWSD** [comment]
Fully integrated v0.6.0 and things work beautifully. Yea, this issue can be closed for sure! Your code makes the lights go on for my classes and students! THANK YOU!

**Comment by siteswapjuggler** [comment]
It's a nice reward to see that this Library please people around the globe :) Thanks for your comment.

Have a nice day
Sylvain
