### ISSUE TITLE
ramp variable conversion

### ISSUE THREAD

**Issue by maxmorelli27** [siteswapjuggler/RAMP#21]
Hi everyone, 
I have a problem, i can't find a way to use the ramp (nor rampInt) variable as a simple int, i'd like to use it to control some servo motors.
Thanks for the help.

**Comment by siteswapjuggler** [comment]
I don't understand what you're trying to do here. If you want to use a simple int why not using an int ? rampInt is an object with it's own rules and doesn't overload basic operators so you have to use set and get methods to make something similar to the basic types attribution and operation.

**Comment by maxmorelli27** [comment]
So I can use a normal int as my ramp object?

**Comment by siteswapjuggler** [comment]
Nope and still do not understand what you are trying to do. Can you share an example code of what you try to achieve and describe what exactly doesn't work as you'd expect ?

**Comment by maxmorelli27** [comment]
I get it now, it works thank you so much, sorry for the dumb question 😅
