### ISSUE TITLE
Not working in PlatformIO nor ArduinoIDE 2.0

### ISSUE THREAD

**Issue by kleurbleur** [siteswapjuggler/RAMP#23]
All latest versions. 

Basic code as shown below: 

```
#include <Arduino.h> // only for PlatformIO otherwise delete
#include <Ramp.h>

ramp myRamp;

void setup()
{
  Serial.begin(115200);
  myRamp.go(4096, 5000);

}

void loop()
{

  Serial.println(myRamp.update());

}
```

**Comment by siteswapjuggler** [comment]
Hmmm it's strange as <Arduino.h> is already included in the Ramp.h file so it would mean that this a main architecture change in the ino file which seems a very unlikely move from Arduino... I'll investigate.

**Comment by siteswapjuggler** [comment]
Actually we could probably include it anyway as the precomp will ignore it, thanks for your comment, Library updated.
