### ISSUE TITLE
Set ramp_mode with a variable

### ISSUE THREAD

**Issue by mircose** [siteswapjuggler/RAMP#25]
Hi, Thanks for your library

I want to set ramp_mode with a variable like:

int myRampMode=LINEAR;
myRamp.go(100, 10000, myRampMode);

but I receive this error message:
invalid conversion from 'int' to 'ramp_mode' [-fpermissive]

any solution?

**Comment by siteswapjuggler** [comment]
Actually your message is just a warning, it should compile without problem.

But if you want to do it the proper way juste use a type conversion or the proper enum type :
int myRampMode = (int)LINEAR or ramp_mode myRampMode = LINEAR

Either should get rid of the warning.

Have a nice day

**Comment by mircose** [comment]
Thanks a lot
