### ISSUE TITLE
Looping does not work properly

### ISSUE THREAD

**Issue by prampec** [siteswapjuggler/RAMP#26]
There is a problem with LOOPFORWARD and LOOPBACKWARD. Mainly we skip one value from the loop.

Here is a very basic test program to reproduce the problem:
```
#include <Arduino.h>
#include <Ramp.h>

rampInt r;

void setup()
{
  Serial.begin(115200);

  r.go(255, 5000, LINEAR, LOOPFORWARD);
}

void loop()
{
  int val = r.update(); // Store the current value
  Serial.print(r.getPosition()); // Get the actual time the value was calculated
  Serial.print(" ");
  Serial.print(val);
  Serial.println();
  delay(100);
}
```

With this - you can see in the console - the first batch starts okay, like this:
```
0 0
100 5
200 10
...
```
Now, if you scroll down to the end of the first batch and to the second batch, it looks something like this:
```
4900 250
0 255
100 5
200 10
...
```

So, there is already two problems here (originated from the same bug).
1. The position 5000 is actually never reached, as it was immediately changed to zero, so value 255 appeared under position 0.
2. Value zero is missing from the second batch: pos zero is not calculated.

The cause of this is the `pos=0` in the `isFinished()` under `LOOPFORWARD`
https://github.com/siteswapjuggler/RAMP/blob/903359ae1899c5032c2a0265cd5acb2fad9f77e9/src/Ramp.cpp#L86
Unfortunately I cannot offer a correct bugfix for this, but solution could be something like this: after finish, we should keep the value of `pos` at `dur`, and only one iteration later should we switch it to 0 while calculating the value for pos zero. (I will think on that and might came back with a proper solution.)

(Of course the same stands for LOOPBACKWARD.)

**Comment by siteswapjuggler** [comment]
Hmmm actually it seems like a priority problem I'll test a correction by tonight.

**Comment by prampec** [comment]
In my opinion LOOPFORWARD and LOOPBACKWARD are not very useful after all. You might want remove them completely, to keep things simple. :)

**Comment by siteswapjuggler** [comment]
Not usefull for you doesn't mean not usefull for others, I'll not remove them, but I can clarify how they work and make them better aligned with our needs.

**Comment by siteswapjuggler** [comment]
I just made a new release and I did put the isFinished() test before updating the value in order for the destination value to be reached at duration time before being reset in the next call.

Please note that depending on the grain setting (10 ms by default), the duration of the ramp and the delays within your code it can miss the 0 value on next loop... I do add a new example to show off a loopforward example without delays and with the minimum grain value.
