### ISSUE TITLE
Feature idea

### ISSUE THREAD

**Issue by Daniii438** [siteswapjuggler/RAMP#8]
Hello, 

Im sorry im not familiar with github. Would it be possible to add a function to the library which returns the current percentage of how much of the ramp has been completed? 

Aka a 2s ramp would return 0.5 after 1s showing that the ramp is 50% done.

Sorry i dont know how i would go about implementing it.

**Comment by siteswapjuggler** [comment]
Nice idea, I don't have any microcontroller to test it right now but I just updated a dev branch with a completion() method that should give you the completion percentage.

**Comment by Daniii438** [comment]
I'll Test it and report back

**Comment by Daniii438** [comment]
Ramp.cpp:40:13: error: 'T' was not declared in this scope
 float _ramp<T>::completion() {
Ramp.cpp:40:14: error: template argument 1 is invalid
 float _ramp<T>::completion() {
Ramp.cpp: In function 'float completion()':
Ramp.cpp:41:14: error: 'pos' was not declared in this scope
  float val = pos*10000/duration;
Ramp.cpp:41:14: note: suggested alternative: 'pow'
  float val = pos*10000/duration;
Ramp.cpp:41:24: error: 'duration' was not declared in this scope
  float val = pos*10000/duration;
Ramp.cpp:41:24: note: suggested alternative: 'union'
  float val = pos*10000/duration;
Ramp.cpp:42:8: error: expected unqualified-id before '/=' token
  float /= 100.;

exit status 1
Error compiling for board Arduino/Genuino Uno.

**Comment by Daniii438** [comment]
i have fixed it and opened a pull request.

**Comment by siteswapjuggler** [comment]
fixed in dev branch
